### PR TITLE
feat: create identify to firewall

### PR DESCRIPTION
**Pull request by rafael-dev2021**
# Description

## PR Checklist
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe: 

## Expected Behavior:
- Query firewalls of WordPress web pages.

## What is the current behavior?
- The code is working perfectly, it's doing what it was designed to do, search and confirm firewalls on Wordpress sites.

## What is the new behavior?
- N/A

# Other information
## Current code
c

## How the code is working
c

## Unit tests
c

## Coverage
c

### CODE REVIEW

**Review by blackcrw — CHANGES_REQUESTED** [review]
The use of goroutines is interesting, but for this function it is not very interesting because as we are trying to identify a firewall without raising too many suspicions (even though we are making direct requests to the firewall's root folder); and it is also interesting to use gnet instead of the native library even though it has more features.

**Review by ygorsimoes — CHANGES_REQUESTED** [review]
If `codecov/project` fails it is possible that your code does not have enough tests. Therefore, be sure to create tests for the code you are creating.

**Comment by rafael-dev2021** [comment]
# Description

## PR Checklist
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
- [x] Code style update (formatting, local variables)

## What is the current behavior?
- The code is working perfectly, it's doing what it was designed to do, search and confirm firewalls on Wordpress sites.

## Issue Number: #32 

## What is the new behavior?
- N/A

# Other information
## Current code
c

## How the code is working
c

## Unit tests
c

## Coverage
c

**Review by blackcrw — CHANGES_REQUESTED** [review]

**Review by ygorsimoes — APPROVED** [review]
LGTM

**Pull request merged**
