### PR TITLE
feat: config.go created

### PR DESCRIPTION
**Pull request by wendoxx**
'config.yaml' converted to 'config yml' & added the function 'GetVersion'.

### CODE REVIEW

**Review by ygorsimoes — CHANGES_REQUESTED** [review]
**It's that way!** Don't forget to create tests and document your code and also take a look at the [NOMENCLATURE](https://github.com/institute-atri/.docs/blob/main/docs/NOMENCLATURE.md) documentation to check the standardization of commits, issues, PRs, etc... Keep the standard!

**Comment by wendoxx** [comment]
# Description

## Issue number: #40 

# Whats is the current behavior?
The code is working perfectly. It's able to access the config.yml file and return the version in the GetVersion function.

# Other information
## Current code
codigo_config

## Unit test
test_config

**Review by ygorsimoes — APPROVED** [review]
LGTM

**Comment by wendoxx** [comment]
# Description

## Issue number: #40 

# Whats is the current behavior?
The code is working perfectly. It's able to access the config.yml file and return the version in the GetVersion function.

# Other information
## Current code
codigo_config

## Unit test
Now there are 2 unit tests. The first one tests the GetVersion function, and the second one tests the LoadConfig function.
test_config

Screenshot from 2024-03-20 20-22-25

**Pull request merged**
